add_team: Team aded
share: Shared on facebook
sign_in: Signed in
view:
  home: View home page
  sign_up: View landing page
  edit: View edit page
update_team: Team updated
updated_profile: Profile updated
